[project]
name = "symbolic-agi"
version = "0.1.0"
description = "A symbolic AGI architecture for complex reasoning and self-improvement."
authors = [{ name = "Todd Goldfarb", email = "todd.goldfarb@example.com" }]
requires-python = ">=3.11"
dependencies = [
    "openai",
    "pydantic",
    "numpy",
    "faiss-cpu",
    "aiofiles",
    "colorlog",
    "prometheus-client",
    "playwright",
    "requests",
    "beautifulsoup4",
    "duckduckgo-search",
    "watchfiles",
]

[project.optional-dependencies]
dev = [
    "pytest",
    "pytest-asyncio",
    "mypy",
    "ruff",
    "pre-commit",
    "memory-profiler",
]

[tool.setuptools.packages.find]
where = ["."]

[tool.ruff]
line-length = 88

[tool.ruff.lint]
select = ["E", "W", "F", "I", "C", "B"]
ignore = ["E501"]

[tool.mypy]
python_version = "3.11"
warn_return_any = true
warn_unused_configs = true
ignore_missing_imports = true
strict = true

[[tool.mypy.overrides]]
module = "faiss"
ignore_missing_imports = true